/**
 * Demo Data for CSM Task Queue
 *
 * Provides realistic sample data for demonstration purposes when API returns empty.
 */

import type {
  CSMQueueTask,
  CSMTaskType,
  CSMPlaybook,
  CSMWeeklyOutcomes,
  CSMTaskWithContext,
} from "../../../../api/types/customerSuccess";

// ============================================
// Task Types with Quality Gates
// ============================================

export const demoTaskTypes: CSMTaskType[] = [
  {
    id: 1,
    name: "Onboarding Stall Recovery",
    slug: "onboarding_stall",
    description: "Customer has stalled during onboarding for 7+ days",
    category: "onboarding",
    default_priority: "urgent",
    sla_hours: 24,
    playbook_id: 1,
    required_outcomes: ["completed_step", "scheduled_followup"],
    quality_gates: [
      {
        id: "q1",
        question: "Did customer complete the missing step?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "What is the specific blocker?",
        gate_type: "text",
        required: false,
        order: 2,
      },
      {
        id: "q3",
        question: "Is follow-up scheduled?",
        gate_type: "boolean",
        required: true,
        order: 3,
      },
    ],
    auto_trigger_conditions: { onboarding_incomplete_days: 7 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Day 30 Check-in",
    slug: "day_30_checkin",
    description: "Confirm customer is realizing value at 30 days",
    category: "adoption",
    default_priority: "high",
    sla_hours: 48,
    playbook_id: 2,
    required_outcomes: ["value_confirmed", "friction_identified"],
    quality_gates: [
      {
        id: "q1",
        question: "Did customer confirm value received?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Is customer on track for renewal?",
        gate_type: "select",
        required: true,
        options: ["Yes", "No", "Unsure"],
        order: 2,
      },
      {
        id: "q3",
        question: "Any expansion opportunities identified?",
        gate_type: "boolean",
        required: true,
        order: 3,
      },
      {
        id: "q4",
        question: "Expansion notes",
        gate_type: "text",
        required: false,
        order: 4,
      },
    ],
    auto_trigger_conditions: { days_since_signup: 30 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 3,
    name: "At-Risk Recovery",
    slug: "at_risk_recovery",
    description: "Customer showing signs of churn risk",
    category: "retention",
    default_priority: "urgent",
    sla_hours: 24,
    playbook_id: 3,
    required_outcomes: ["root_cause_identified", "recovery_action"],
    quality_gates: [
      {
        id: "q1",
        question: "Root cause identified?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Primary risk factor",
        gate_type: "select",
        required: true,
        options: [
          "Low usage",
          "Support issues",
          "Budget",
          "Champion left",
          "Competition",
          "Other",
        ],
        order: 2,
      },
      {
        id: "q3",
        question: "Recovery action taken?",
        gate_type: "boolean",
        required: true,
        order: 3,
      },
      {
        id: "q4",
        question: "Customer retained?",
        gate_type: "select",
        required: true,
        options: ["Yes - saved", "Yes - at risk", "No - churned", "Pending"],
        order: 4,
      },
    ],
    auto_trigger_conditions: { health_score_below: 40 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 4,
    name: "Day 60 Check-in",
    slug: "day_60_checkin",
    description: "Mid-journey adoption check",
    category: "adoption",
    default_priority: "standard",
    sla_hours: 72,
    playbook_id: 4,
    required_outcomes: ["adoption_review"],
    quality_gates: [
      {
        id: "q1",
        question: "Feature adoption improving?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Additional training needed?",
        gate_type: "boolean",
        required: false,
        order: 2,
      },
    ],
    auto_trigger_conditions: { days_since_signup: 60 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 5,
    name: "Day 90 QBR",
    slug: "day_90_qbr",
    description: "Quarterly business review",
    category: "retention",
    default_priority: "high",
    sla_hours: 48,
    playbook_id: 5,
    required_outcomes: ["qbr_completed", "next_quarter_goals"],
    quality_gates: [
      {
        id: "q1",
        question: "QBR meeting held?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Customer satisfied with ROI?",
        gate_type: "select",
        required: true,
        options: ["Very satisfied", "Satisfied", "Neutral", "Dissatisfied"],
        order: 2,
      },
      {
        id: "q3",
        question: "Next quarter goals set?",
        gate_type: "boolean",
        required: true,
        order: 3,
      },
    ],
    auto_trigger_conditions: { days_since_signup: 90 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 6,
    name: "Renewal Preparation",
    slug: "renewal_prep",
    description: "Prepare for upcoming renewal",
    category: "renewal",
    default_priority: "urgent",
    sla_hours: 48,
    playbook_id: 6,
    required_outcomes: ["renewal_intent", "pricing_discussion"],
    quality_gates: [
      {
        id: "q1",
        question: "Customer intends to renew?",
        gate_type: "select",
        required: true,
        options: ["Yes", "Likely", "Unlikely", "No", "Unknown"],
        order: 1,
      },
      {
        id: "q2",
        question: "Pricing concerns?",
        gate_type: "boolean",
        required: true,
        order: 2,
      },
      {
        id: "q3",
        question: "Expansion discussed?",
        gate_type: "boolean",
        required: false,
        order: 3,
      },
    ],
    auto_trigger_conditions: { days_to_renewal: 60 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 7,
    name: "NPS Detractor Follow-up",
    slug: "nps_detractor_followup",
    description: "Follow up on negative NPS score",
    category: "retention",
    default_priority: "urgent",
    sla_hours: 24,
    playbook_id: 7,
    required_outcomes: ["issue_understood", "resolution_provided"],
    quality_gates: [
      {
        id: "q1",
        question: "Issue understood?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Resolution provided?",
        gate_type: "boolean",
        required: true,
        order: 2,
      },
      {
        id: "q3",
        question: "Customer sentiment improved?",
        gate_type: "select",
        required: true,
        options: ["Yes", "Somewhat", "No", "Unknown"],
        order: 3,
      },
    ],
    auto_trigger_conditions: { nps_score_below: 7 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 8,
    name: "Expansion Opportunity",
    slug: "expansion_opportunity",
    description: "Explore expansion with healthy customer",
    category: "expansion",
    default_priority: "standard",
    sla_hours: 72,
    playbook_id: 8,
    required_outcomes: ["opportunity_qualified"],
    quality_gates: [
      {
        id: "q1",
        question: "Expansion opportunity qualified?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Opportunity value ($)",
        gate_type: "text",
        required: false,
        order: 2,
      },
      {
        id: "q3",
        question: "Next steps defined?",
        gate_type: "boolean",
        required: true,
        order: 3,
      },
    ],
    auto_trigger_conditions: { health_score_above: 80 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
  {
    id: 9,
    name: "Health Score Drop",
    slug: "health_score_drop",
    description: "Health score dropped significantly",
    category: "retention",
    default_priority: "high",
    sla_hours: 24,
    playbook_id: 3,
    required_outcomes: ["cause_identified"],
    quality_gates: [
      {
        id: "q1",
        question: "Cause of drop identified?",
        gate_type: "boolean",
        required: true,
        order: 1,
      },
      {
        id: "q2",
        question: "Action plan created?",
        gate_type: "boolean",
        required: true,
        order: 2,
      },
    ],
    auto_trigger_conditions: { health_score_drop_percent: 15 },
    is_active: true,
    created_at: "2025-12-01T00:00:00Z",
  },
];

// ============================================
// CSM Playbooks with Scripts and Objection Handlers
// ============================================

export const demoPlaybooks: CSMPlaybook[] = [
  {
    id: 1,
    task_type_id: 1,
    name: "Onboarding Stall Recovery",
    version: "1.0",
    objective: "Get customer to complete the missing onboarding step today",
    context_fields: [
      "signup_date",
      "completed_steps",
      "missing_steps",
      "last_contact",
      "customer_notes",
    ],
    opening_script:
      "Hi [name], this is [csm] from ECBTX. I noticed you started setup but haven't gotten to [missing_step] yet. That's actually the part that unlocks the most value for your team. Do you have 10 minutes? I can walk you through it now.",
    key_questions: [
      "What's been keeping you from completing setup?",
      "Is there anything confusing about the process?",
      "What are you hoping to achieve with our product?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Been busy/traveling",
        response:
          "Totally understand. The setup takes just 5 minutes - can we knock it out right now while we're talking?",
        order: 1,
      },
      {
        id: "o2",
        trigger: "I'll do it later",
        response:
          "I hear you. The risk is that your team won't see value until this is done. Let's at least get started together.",
        order: 2,
      },
      {
        id: "o3",
        trigger: "Having technical issues",
        response:
          "Let me help with that right now. Can you share your screen so we can troubleshoot together?",
        order: 3,
      },
      {
        id: "o4",
        trigger: "Not sure I need this",
        response:
          "That's fair to question. The reason this step matters is it connects your data to our insights engine. Can I show you what that looks like?",
        order: 4,
      },
    ],
    success_criteria:
      "Customer completes missing step OR concrete follow-up scheduled within 48 hours",
    estimated_duration_minutes: 15,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 2,
    task_type_id: 2,
    name: "Day 30 Check-in",
    version: "1.0",
    objective: "Confirm customer is realizing value, identify any friction",
    context_fields: [
      "signup_date",
      "adoption_metrics",
      "feature_usage",
      "health_score",
      "recent_interactions",
    ],
    opening_script:
      "Hi [name], it's been about a month since you started with us. I wanted to check in and see how things are going. What's been most useful so far?",
    key_questions: [
      "What's been most valuable?",
      "Anything confusing or frustrating?",
      "Anyone else who should have access?",
      "Any upcoming needs we should know about?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Haven't had time to use it",
        response:
          "I understand time is limited. Let's identify one quick win you can achieve this week.",
        order: 1,
      },
      {
        id: "o2",
        trigger: "It's more complicated than expected",
        response:
          "That's valuable feedback. Can you tell me which part was confusing? I'll make sure we address it.",
        order: 2,
      },
    ],
    success_criteria:
      "Customer confirms value OR friction identified and logged for follow-up",
    estimated_duration_minutes: 20,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 3,
    task_type_id: 3,
    name: "At-Risk Recovery",
    version: "1.0",
    objective: "Understand root cause, create recovery plan, prevent churn",
    context_fields: [
      "health_score_history",
      "risk_factors",
      "recent_tickets",
      "usage_decline",
      "payment_issues",
    ],
    opening_script:
      "Hi [name], I wanted to reach out personally. I noticed [specific signal - usage drop/missed payment/low score]. I want to make sure we're delivering what you need. Can we talk about what's going on?",
    key_questions: [
      "What's changed since you started using us?",
      "What would need to happen for this to be successful for you?",
      "Is there anything we could do differently?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Thinking of canceling",
        response:
          "I appreciate you being direct. Before you decide, can you help me understand what's not working? I may be able to fix it.",
        order: 1,
      },
      {
        id: "o2",
        trigger: "Not getting value",
        response:
          "That's on us. What did you expect that you're not seeing? Let's figure out how to get you there.",
        order: 2,
      },
      {
        id: "o3",
        trigger: "Too expensive",
        response:
          "I understand budget matters. Let's look at what you're actually using and see if there's a better fit.",
        order: 3,
      },
      {
        id: "o4",
        trigger: "Switching to competitor",
        response:
          "I'd hate to lose you. What does their solution offer that we don't? Sometimes we can match it.",
        order: 4,
      },
    ],
    success_criteria:
      "Root cause identified, recovery action taken, follow-up scheduled",
    estimated_duration_minutes: 30,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 4,
    task_type_id: 4,
    name: "Day 60 Check-in",
    version: "1.0",
    objective: "Review adoption progress and address gaps",
    context_fields: ["adoption_metrics", "feature_usage", "health_score"],
    opening_script:
      "Hi [name], it's been about two months now. I wanted to check how your team is progressing with the platform.",
    key_questions: [
      "Which features is your team using most?",
      "Are there features you wanted to use but havent yet?",
      "How is the team adapting to the new workflow?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Team isn't adopting",
        response:
          "Let's identify the blockers. Would a team training session help?",
        order: 1,
      },
    ],
    success_criteria:
      "Adoption progress reviewed, gaps identified and addressed",
    estimated_duration_minutes: 20,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 5,
    task_type_id: 5,
    name: "Quarterly Business Review (QBR)",
    version: "1.0",
    objective: "Conduct structured business review, confirm renewal trajectory",
    context_fields: [
      "usage_summary",
      "roi_metrics",
      "health_score",
      "open_issues",
      "expansion_opportunities",
    ],
    opening_script:
      "Thank you for joining the QBR. Today I'd like to review the value we've delivered, discuss any open issues, and align on goals for next quarter.",
    key_questions: [
      "How would you rate your overall experience this quarter?",
      "What's the biggest impact we've had on your business?",
      "What are your priorities for next quarter?",
      "Are there areas where we could be doing more?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Haven't seen the ROI",
        response:
          "Let's look at the metrics together. Sometimes value shows up in ways we haven't measured yet.",
        order: 1,
      },
      {
        id: "o2",
        trigger: "Budget concerns for renewal",
        response:
          "I understand. Let's make sure you're getting maximum value from your current plan before discussing options.",
        order: 2,
      },
    ],
    success_criteria:
      "QBR completed, renewal intent confirmed, next steps documented",
    estimated_duration_minutes: 45,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 6,
    task_type_id: 6,
    name: "Renewal Preparation",
    version: "1.0",
    objective: "Secure renewal commitment and discuss expansion",
    context_fields: [
      "contract_value",
      "renewal_date",
      "health_score",
      "usage_metrics",
      "expansion_opportunities",
    ],
    opening_script:
      "Hi [name], your renewal is coming up in [X] days. I wanted to connect to make sure everything is in order and discuss how we can continue supporting your success.",
    key_questions: [
      "How would you describe the value you've received?",
      "Are there any concerns about renewing?",
      "Any additional needs we should factor into your renewal?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Need to think about it",
        response: "Of course. What questions can I answer to help you decide?",
        order: 1,
      },
      {
        id: "o2",
        trigger: "Looking at alternatives",
        response:
          "I'd love to understand what's driving that. Can we discuss what might keep you with us?",
        order: 2,
      },
      {
        id: "o3",
        trigger: "Need a discount",
        response:
          "Let me see what I can do. Can you help me understand your budget constraints?",
        order: 3,
      },
    ],
    success_criteria:
      "Renewal intent confirmed or concerns documented for resolution",
    estimated_duration_minutes: 25,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 7,
    task_type_id: 7,
    name: "NPS Detractor Follow-up",
    version: "1.0",
    objective: "Understand dissatisfaction, resolve issue, flip to promoter",
    context_fields: [
      "nps_score",
      "nps_comment",
      "recent_tickets",
      "health_score",
      "tenure",
    ],
    opening_script:
      "Hi [name], thank you for your honest feedback on our survey. You mentioned [paraphrase comment]. I'd like to understand more and see what we can do to make this right.",
    key_questions: [
      "Can you tell me more about what drove that score?",
      "What would need to change for you to feel differently?",
      "Is there anything specific we can fix right now?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "Don't want to talk about it",
        response:
          "I respect that. If you change your mind, I'm here to help. Is there anything I can do via email instead?",
        order: 1,
      },
      {
        id: "o2",
        trigger: "It's too late",
        response:
          "I understand your frustration. Before you go, can I try to make it right?",
        order: 2,
      },
    ],
    success_criteria:
      "Issue understood, resolution provided or escalated, follow-up sentiment captured",
    estimated_duration_minutes: 20,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
  {
    id: 8,
    task_type_id: 8,
    name: "Expansion Opportunity",
    version: "1.0",
    objective: "Qualify expansion opportunity with satisfied customer",
    context_fields: [
      "current_plan",
      "usage_metrics",
      "health_score",
      "team_size",
      "growth_signals",
    ],
    opening_script:
      "Hi [name], I've noticed your team has been getting great results. I wanted to explore if there are ways we could support your growth further.",
    key_questions: [
      "Are there other teams who could benefit from the platform?",
      "What additional capabilities would be most valuable?",
      "Do you have budget for expansion this quarter?",
    ],
    objection_handlers: [
      {
        id: "o1",
        trigger: "No budget right now",
        response:
          "Understood. When do you typically plan for new investments? Let's schedule a follow-up.",
        order: 1,
      },
      {
        id: "o2",
        trigger: "Need to see more value first",
        response:
          "That makes sense. What would convince you? Let's set a success milestone.",
        order: 2,
      },
    ],
    success_criteria: "Expansion opportunity qualified, next steps defined",
    estimated_duration_minutes: 20,
    is_active: true,
    updated_at: "2025-12-15T00:00:00Z",
  },
];

// ============================================
// Demo Queue Tasks (sorted by priority_score DESC)
// ============================================

const today = new Date();
const formatDate = (offset: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().split("T")[0];
};

export const demoQueueTasks: CSMQueueTask[] = [
  // URGENT - At-Risk Recovery
  {
    id: 1,
    customer_id: "101",
    csm_id: 1,
    task_type_id: 3,
    task_type_slug: "at_risk_recovery",
    task_type_name: "At-Risk Recovery",
    priority: "urgent",
    priority_score: 245,
    status: "pending",
    due_date: formatDate(-2), // 2 days overdue
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 3,
    customer_name: "Acme Corp",
    customer_email: "john@acmecorp.com",
    customer_arr: 48000,
    customer_health_score: 35,
    customer_health_status: "critical",
    customer_tier: "high_value",
    customer_renewal_date: formatDate(45),
    days_overdue: 2,
    created_at: formatDate(-5),
    started_at: null,
    completed_at: null,
    metadata: { risk_signals: ["Usage dropped 40%", "No login 14 days"] },
  },
  // URGENT - NPS Detractor
  {
    id: 2,
    customer_id: "102",
    csm_id: 1,
    task_type_id: 7,
    task_type_slug: "nps_detractor_followup",
    task_type_name: "NPS Detractor Follow-up",
    priority: "urgent",
    priority_score: 220,
    status: "pending",
    due_date: formatDate(-1), // 1 day overdue
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 7,
    customer_name: "TechStart Inc",
    customer_email: "sarah@techstart.io",
    customer_arr: 24000,
    customer_health_score: 45,
    customer_health_status: "at_risk",
    customer_tier: "standard",
    customer_renewal_date: formatDate(90),
    days_overdue: 1,
    created_at: formatDate(-3),
    started_at: null,
    completed_at: null,
    metadata: {
      nps_score: 3,
      nps_comment: "Support is slow, features missing",
    },
  },
  // URGENT - Renewal Prep (30 days out)
  {
    id: 3,
    customer_id: "103",
    csm_id: 1,
    task_type_id: 6,
    task_type_slug: "renewal_prep",
    task_type_name: "Renewal Preparation",
    priority: "urgent",
    priority_score: 195,
    status: "pending",
    due_date: formatDate(0), // Due today
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 6,
    customer_name: "Global Services Ltd",
    customer_email: "mike@globalservices.com",
    customer_arr: 96000,
    customer_health_score: 72,
    customer_health_status: "healthy",
    customer_tier: "vip",
    customer_renewal_date: formatDate(28),
    days_overdue: 0,
    created_at: formatDate(-7),
    started_at: null,
    completed_at: null,
    metadata: { contract_years: 2, expansion_discussed: false },
  },
  // URGENT - Onboarding Stall
  {
    id: 4,
    customer_id: "104",
    csm_id: 1,
    task_type_id: 1,
    task_type_slug: "onboarding_stall",
    task_type_name: "Onboarding Stall Recovery",
    priority: "urgent",
    priority_score: 180,
    status: "pending",
    due_date: formatDate(0),
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 1,
    customer_name: "Startup Vision",
    customer_email: "alex@startupvision.co",
    customer_arr: 12000,
    customer_health_score: 50,
    customer_health_status: "at_risk",
    customer_tier: "standard",
    customer_renewal_date: formatDate(335),
    days_overdue: 0,
    created_at: formatDate(-10),
    started_at: null,
    completed_at: null,
    metadata: {
      completed_steps: ["signup", "profile"],
      missing_steps: ["integration", "first_workflow"],
    },
  },
  // HIGH - Day 30 Check-in
  {
    id: 5,
    customer_id: "105",
    csm_id: 1,
    task_type_id: 2,
    task_type_slug: "day_30_checkin",
    task_type_name: "Day 30 Check-in",
    priority: "high",
    priority_score: 145,
    status: "pending",
    due_date: formatDate(1),
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 2,
    customer_name: "DataDriven Co",
    customer_email: "emma@datadriven.co",
    customer_arr: 36000,
    customer_health_score: 68,
    customer_health_status: "healthy",
    customer_tier: "high_value",
    customer_renewal_date: formatDate(335),
    days_overdue: null,
    created_at: formatDate(-2),
    started_at: null,
    completed_at: null,
    metadata: { signup_date: formatDate(-30), adoption_score: 65 },
  },
  // HIGH - Health Score Drop
  {
    id: 6,
    customer_id: "106",
    csm_id: 1,
    task_type_id: 9,
    task_type_slug: "health_score_drop",
    task_type_name: "Health Score Drop",
    priority: "high",
    priority_score: 130,
    status: "pending",
    due_date: formatDate(1),
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 3,
    customer_name: "MidMarket Solutions",
    customer_email: "david@midmarket.com",
    customer_arr: 28000,
    customer_health_score: 52,
    customer_health_status: "at_risk",
    customer_tier: "standard",
    customer_renewal_date: formatDate(120),
    days_overdue: null,
    created_at: formatDate(-1),
    started_at: null,
    completed_at: null,
    metadata: { previous_score: 78, drop_percent: 33 },
  },
  // HIGH - QBR
  {
    id: 7,
    customer_id: "107",
    csm_id: 1,
    task_type_id: 5,
    task_type_slug: "day_90_qbr",
    task_type_name: "Day 90 QBR",
    priority: "high",
    priority_score: 115,
    status: "in_progress",
    due_date: formatDate(2),
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 5,
    customer_name: "Enterprise Plus",
    customer_email: "jennifer@enterpriseplus.com",
    customer_arr: 120000,
    customer_health_score: 82,
    customer_health_status: "healthy",
    customer_tier: "vip",
    customer_renewal_date: formatDate(275),
    days_overdue: null,
    created_at: formatDate(-5),
    started_at: formatDate(-1),
    completed_at: null,
    metadata: { qbr_scheduled: true, meeting_time: "2:00 PM" },
  },
  // STANDARD - Day 60 Check-in
  {
    id: 8,
    customer_id: "108",
    csm_id: 1,
    task_type_id: 4,
    task_type_slug: "day_60_checkin",
    task_type_name: "Day 60 Check-in",
    priority: "standard",
    priority_score: 75,
    status: "pending",
    due_date: formatDate(3),
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 4,
    customer_name: "Growth Labs",
    customer_email: "tom@growthlabs.io",
    customer_arr: 18000,
    customer_health_score: 70,
    customer_health_status: "healthy",
    customer_tier: "standard",
    customer_renewal_date: formatDate(305),
    days_overdue: null,
    created_at: formatDate(-1),
    started_at: null,
    completed_at: null,
    metadata: { signup_date: formatDate(-60) },
  },
  // STANDARD - Expansion Opportunity
  {
    id: 9,
    customer_id: "109",
    csm_id: 1,
    task_type_id: 8,
    task_type_slug: "expansion_opportunity",
    task_type_name: "Expansion Opportunity",
    priority: "standard",
    priority_score: 65,
    status: "pending",
    due_date: formatDate(5),
    snooze_until: null,
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 8,
    customer_name: "Innovate Inc",
    customer_email: "lisa@innovateinc.com",
    customer_arr: 42000,
    customer_health_score: 88,
    customer_health_status: "healthy",
    customer_tier: "high_value",
    customer_renewal_date: formatDate(180),
    days_overdue: null,
    created_at: formatDate(-3),
    started_at: null,
    completed_at: null,
    metadata: {
      expansion_signals: [
        "3 new team members",
        "Asking about enterprise features",
      ],
    },
  },
  // LOW - Day 30 Check-in (snoozed)
  {
    id: 10,
    customer_id: "110",
    csm_id: 1,
    task_type_id: 2,
    task_type_slug: "day_30_checkin",
    task_type_name: "Day 30 Check-in",
    priority: "low",
    priority_score: 35,
    status: "snoozed",
    due_date: formatDate(7),
    snooze_until: formatDate(3),
    outcome_type: null,
    objective_achieved: null,
    outcome_notes: null,
    sentiment: null,
    next_action: null,
    next_action_date: null,
    quality_gates_completed: null,
    playbook_id: 2,
    customer_name: "Small Biz Co",
    customer_email: "owner@smallbiz.co",
    customer_arr: 6000,
    customer_health_score: 60,
    customer_health_status: "healthy",
    customer_tier: "low_value",
    customer_renewal_date: formatDate(335),
    days_overdue: null,
    created_at: formatDate(-5),
    started_at: null,
    completed_at: null,
    metadata: { snooze_reason: "Customer on vacation" },
  },
];

// ============================================
// Weekly Outcomes Demo Data
// ============================================

const getWeekStart = () => {
  const d = new Date();
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  d.setDate(diff);
  return d.toISOString().split("T")[0];
};

const getWeekEnd = () => {
  const d = new Date();
  const day = d.getDay();
  const diff = d.getDate() - day + 7;
  d.setDate(diff);
  return d.toISOString().split("T")[0];
};

export const demoWeeklyOutcomes: CSMWeeklyOutcomes = {
  period_start: getWeekStart(),
  period_end: getWeekEnd(),
  outcomes: {
    onboarding_completions: { actual: 4, goal: 5 },
    at_risk_saves: { actual: 2, goal: 3 },
    health_improvements: 7,
    renewals_secured: { amount: 144000, count: 3 },
    expansion_pipeline: { amount: 36000, count: 2 },
  },
  activity: {
    calls_made: 28,
    emails_sent: 45,
    tasks_completed: 18,
  },
  comparison: {
    team_average: 72,
    your_score: 85,
    percentile: 80,
  },
  trend_vs_last_week: 12,
};

// ============================================
// Task with Full Context (for detail view)
// ============================================

export const demoTaskWithContext: CSMTaskWithContext = {
  task: demoQueueTasks[0], // At-Risk Recovery task
  task_type: demoTaskTypes.find((t) => t.slug === "at_risk_recovery")!,
  playbook: demoPlaybooks.find((p) => p.id === 3)!,
  customer: {
    id: 101,
    name: "Acme Corp",
    email: "john@acmecorp.com",
    phone: "+1 (555) 123-4567",
    arr: 48000,
    health_score: 35,
    health_status: "critical",
    tier: "high_value",
    renewal_date: formatDate(45),
    churn_probability: 0.65,
    days_since_last_contact: 14,
    contacts: [
      {
        name: "John Smith",
        email: "john@acmecorp.com",
        role: "VP Operations",
        is_champion: true,
      },
      {
        name: "Sarah Johnson",
        email: "sarah@acmecorp.com",
        role: "IT Manager",
        is_champion: false,
      },
    ],
  },
  interaction_history: [
    {
      id: 1001,
      customer_id: "101",
      touchpoint_type: "call_outbound",
      subject: "Check-in call",
      summary: "Left voicemail - customer did not answer",
      description: null,
      direction: "outbound",
      channel: "phone",
      user_id: 1,
      user_role: "CSM",
      contact_name: "John Smith",
      contact_email: "john@acmecorp.com",
      contact_role: "VP Operations",
      contact_is_champion: true,
      contact_is_executive: false,
      attendee_count: null,
      sentiment_score: null,
      sentiment_label: null,
      sentiment_confidence: null,
      key_topics: null,
      action_items: null,
      risk_signals: null,
      expansion_signals: null,
      key_quotes: null,
      engagement_score: null,
      was_positive: null,
      duration_minutes: 1,
      start_time: null,
      end_time: null,
      meeting_link: null,
      recording_url: null,
      nps_score: null,
      csat_score: null,
      task_id: null,
      journey_enrollment_id: null,
      playbook_execution_id: null,
      occurred_at: formatDate(-7),
      created_at: formatDate(-7),
      updated_at: formatDate(-7),
    },
    {
      id: 1002,
      customer_id: "101",
      touchpoint_type: "email_sent",
      subject: "Checking in - How can we help?",
      summary: "Sent follow-up email after missed call",
      description: null,
      direction: "outbound",
      channel: "email",
      user_id: 1,
      user_role: "CSM",
      contact_name: "John Smith",
      contact_email: "john@acmecorp.com",
      contact_role: "VP Operations",
      contact_is_champion: true,
      contact_is_executive: false,
      attendee_count: null,
      sentiment_score: null,
      sentiment_label: null,
      sentiment_confidence: null,
      key_topics: null,
      action_items: null,
      risk_signals: null,
      expansion_signals: null,
      key_quotes: null,
      engagement_score: null,
      was_positive: null,
      duration_minutes: null,
      start_time: null,
      end_time: null,
      meeting_link: null,
      recording_url: null,
      nps_score: null,
      csat_score: null,
      task_id: null,
      journey_enrollment_id: null,
      playbook_execution_id: null,
      occurred_at: formatDate(-7),
      created_at: formatDate(-7),
      updated_at: formatDate(-7),
    },
    {
      id: 1003,
      customer_id: "101",
      touchpoint_type: "support_ticket",
      subject: "Integration not working properly",
      summary: "Customer reported data sync issues - resolved in 48 hours",
      description: null,
      direction: "inbound",
      channel: "email",
      user_id: null,
      user_role: null,
      contact_name: "Sarah Johnson",
      contact_email: "sarah@acmecorp.com",
      contact_role: "IT Manager",
      contact_is_champion: false,
      contact_is_executive: false,
      attendee_count: null,
      sentiment_score: -0.3,
      sentiment_label: "negative",
      sentiment_confidence: 0.85,
      key_topics: ["integration", "data sync", "technical issue"],
      action_items: null,
      risk_signals: ["Technical frustration"],
      expansion_signals: null,
      key_quotes: null,
      engagement_score: null,
      was_positive: false,
      duration_minutes: null,
      start_time: null,
      end_time: null,
      meeting_link: null,
      recording_url: null,
      nps_score: null,
      csat_score: null,
      task_id: null,
      journey_enrollment_id: null,
      playbook_execution_id: null,
      occurred_at: formatDate(-21),
      created_at: formatDate(-21),
      updated_at: formatDate(-19),
    },
  ],
};

// Helper function to get task type by slug
export function getTaskType(slug: string): CSMTaskType | undefined {
  return demoTaskTypes.find((t) => t.slug === slug);
}

// Helper function to get playbook by task type
export function getPlaybookForTaskType(
  taskTypeId: number,
): CSMPlaybook | undefined {
  const taskType = demoTaskTypes.find((t) => t.id === taskTypeId);
  if (taskType?.playbook_id) {
    return demoPlaybooks.find((p) => p.id === taskType.playbook_id);
  }
  return undefined;
}
