#!/usr/bin/env python3
"""
MGO Extraction Progress Report Generator
Reads NDJSON files and generates a markdown report
"""

import os
import json
from collections import defaultdict
from datetime import datetime

OUTPUT_DIR = os.path.expanduser("~/mgo_extraction/mgo/scrapers/output/mgo/full_extraction")
REPORT_FILE = os.path.expanduser("~/mgo_extraction/MGO_EXTRACTION_REPORT.md")

def generate_report():
    # Collect data from all NDJSON files
    jurisdictions = {}

    for filename in sorted(os.listdir(OUTPUT_DIR)):
        if not filename.endswith('.ndjson'):
            continue

        filepath = os.path.join(OUTPUT_DIR, filename)
        file_size = os.path.getsize(filepath)

        # Count records and collect project types
        record_count = 0
        project_types = set()
        jurisdiction_name = None
        state = None

        with open(filepath, 'r') as f:
            for line in f:
                if line.strip():
                    record_count += 1
                    if record_count == 1:  # Get metadata from first record
                        try:
                            data = json.loads(line)
                            jurisdiction_name = data.get('_jurisdiction', filename.replace('.ndjson', ''))
                            state = data.get('_state', 'N/A')
                            project_types.add(data.get('_projectType', 'Unknown'))
                        except:
                            pass
                    else:
                        try:
                            data = json.loads(line)
                            project_types.add(data.get('_projectType', 'Unknown'))
                        except:
                            pass

        if jurisdiction_name is None:
            jurisdiction_name = filename.replace('.ndjson', '').replace('_', ' ').title()

        jurisdictions[filename] = {
            'name': jurisdiction_name,
            'state': state or 'N/A',
            'records': record_count,
            'project_types': sorted(project_types),
            'file_size': file_size,
            'filename': filename
        }

    # Group by state
    by_state = defaultdict(list)
    for data in jurisdictions.values():
        by_state[data['state']].append(data)

    # Generate report
    total_records = sum(j['records'] for j in jurisdictions.values())
    total_files = len(jurisdictions)
    total_size = sum(j['file_size'] for j in jurisdictions.values())

    report = f"""# MGO Connect Extraction Progress Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Status:** In Progress

---

## Summary

| Metric | Value |
|--------|-------|
| Total Records Extracted | **{total_records:,}** |
| Jurisdictions Processed | **{total_files}** / 432 |
| Total Data Size | **{total_size / (1024*1024):.2f} MB** |

---

## By State

"""

    for state in sorted(by_state.keys()):
        state_jurisdictions = by_state[state]
        state_total = sum(j['records'] for j in state_jurisdictions)

        report += f"### {state} ({len(state_jurisdictions)} jurisdictions, {state_total:,} records)\n\n"
        report += "| Jurisdiction | Project Types | Records | File |\n"
        report += "|-------------|---------------|---------|------|\n"

        for j in sorted(state_jurisdictions, key=lambda x: x['name']):
            types_str = ', '.join(j['project_types'][:3])
            if len(j['project_types']) > 3:
                types_str += f" (+{len(j['project_types'])-3} more)"
            report += f"| {j['name']} | {types_str} | {j['records']:,} | {j['filename']} |\n"

        report += "\n"

    report += """---

## All Project Types Found

"""
    all_types = set()
    for j in jurisdictions.values():
        all_types.update(j['project_types'])

    for pt in sorted(all_types):
        report += f"- {pt}\n"

    report += f"""
---

*Report auto-generated by generate-report.py*
"""

    # Write report
    with open(REPORT_FILE, 'w') as f:
        f.write(report)

    print(f"Report generated: {REPORT_FILE}")
    print(f"Total records: {total_records:,}")
    print(f"Jurisdictions: {total_files}/432")

if __name__ == '__main__':
    generate_report()
